version: '2.1'
services:
  billingdb:
    image: postgres:10.3
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=billingdb_user
      - POSTGRES_PASSWORD=billingdb_pwd
