swagger: "2.0"
info:
  version: "1.0"
  title: Billing API
  contact:
    name: Allan Silva
    email: allan.tavares@allantavares.com.br
  description: >
    Billing API receives phone calls information and delivers the incoming request
    to be processed in a reliable way.
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /info:
    get:
      description: Get server information
      operationId: phone_bills.billingapi.billing.get_info
      produces:
        - application/json
      responses:
        '200':
          description: Server Information

  /call:
    post:
      description: Receives a call event.
      operationId: phone_bills.billingapi.billing.call_event
      produces:
        - application/json
      parameters:
        - name: call_record
          in: body
          description: Call event.
          required: true
          schema:
            $ref: '#/definitions/CallRecordModel'
      responses:
        '202':
          description: Call record response.
          schema:
            $ref: '#/definitions/TransactionIdResponseModel'
        '404':
          description: Invalid Call Start request.
        '500':
          description: Internal Server Error.

  /bill/{subscriber}/close:
    post:
      description: Close bill for period.
      operationId: phone_bills.billingapi.billing.bill_close
      produces:
        - application/json
      parameters:
        - name: ref_period
          in: body
          description: Reference period.
          required: true
          schema:
            $ref: '#/definitions/RefPeriodModel'
        - name: subscriber
          in: path
          description: Subscriber number.
          required: true
          type: string
          format: phone-number
      responses:
        '202':
          description: Request for close bill accepted and queued for processing.
          schema:
            $ref: '#/definitions/TransactionIdResponseModel'
        '404':
          description: Invalid request.
        '500':
          description: Internal Server Error.

definitions:
  CallRecordModel:
    type: object
    required:
      - id
      - type
      - timestamp
      - call_id
    properties:
      id:
        description: Record unique identificator.
        type: integer
        format: int64
      type:
        description: Indicate if it's a call "start" or "end" record.
        type: string
        enum:
          - start
          - end
      timestamp:
        description: The timestamp of when the event occured.
        type: string
        format: date-time
      call_id:
        description: Unique for each call record pair.
        type: integer
        format: int64
      source:
        description: The subscriber phone number that originated the call.
        type: string
        format: phone-number
      destination:
        description: The phone number receiving the call.
        type: string
        format: phone-number

  TransactionIdResponseModel:
    description: Call record response.
    type: object
    required:
      - transaction_id
    properties:
      transaction_id:
        description: Request transaction id
        type: string

  RefPeriodModel:
    description: Reference period for close the bill.
    type: object
    required:
      - month
      - year
    properties:
      month:
        description: Reference month.
        type: integer
        format: int32
      year:
        description: Reference year.
        type: integer
        format: int32
